### ISSUE TITLE
a bit more styling on button

### ISSUE THREAD

**Issue by vinlegend1** [fire-ui/fire-ui#8]
**Hover effect default on btn class**
I think instead of having a separate class for hover effects... I think we should have it default to the button class

**a hover effect I though of**
```css
.btn:hover{
    box-shadow: 5px 2px 8px;
    transition: 0.4s;
    transition-timing-function: ease-out;
    opacity: .7;
}
```

**onclick effect**
I think an onclick styling would be great for user experience... here's what I've thought of
```css
.btn:active {
    box-shadow: 5px 2px 8px;
    transition: 0.3s;
    transition-timing-function: ease-in;
    opacity: .5;
}
```
I'd like to be assigned to do this... suggestions for better styling are welcome... hehe :)
